name: CI Pipeline

# Trigger the workflow on push or pull request events to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v3
        with:
          path: frontend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20-alpine' # Ensure consistency with your Dockerfile

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --coverage

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Backend Code
        uses: actions/checkout@v3
        with:
          path: backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20-alpine' # Ensure consistency with your Dockerfile

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test -- --coverage

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

  docker-build-push:
    needs: [build-and-test-frontend, build-and-test-backend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: yourdockerhubusername/frontend:latest

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: yourdockerhubusername/backend:latest

  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull yourdockerhubusername/frontend:latest
            docker pull yourdockerhubusername/backend:latest
            docker-compose down
            docker-compose up -d --build